name: MermaidRenderer
options:
  bundleIdPrefix: com.microsoft.tools
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.2"

settings:
  base:
    SWIFT_VERSION: "5.9"
    GENERATE_INFOPLIST_FILE: YES

targets:
  MermaidRenderer:
    type: application
    platform: iOS
    sources:
      - path: Sources
        excludes:
          - "**/*.md"
    resources:
      - path: Sources/Assets.xcassets
      - path: Sources/Resources/mermaid.min.js
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.microsoft.tools.MermaidRenderer
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_NSPhotoLibraryAddUsageDescription: "Save rendered diagrams to Photos"
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""

  MermaidSwiftTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
        excludes:
          - "**/*.md"
    dependencies:
      - target: MermaidRenderer
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.microsoft.tools.MermaidSwiftTests
        GENERATE_INFOPLIST_FILE: YES
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/MermaidRenderer.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/MermaidRenderer"
        BUNDLE_LOADER: "$(TEST_HOST)"
